development:
  default_from: 'tmt@example.com'
  default_url_options:
    host: 'localhost:3000'
test:
  default_from: 'tmt@example.com'
  default_url_options:
    host: 'localhost:3000'
production:
  default_from: <%= ENV["MAILER_DEFAULT_FROM"] %>
  default_url_options:
    host: <%= ENV["MAILER_URL_OPTIONS_HOST"] %>
    port: <%= ENV["MAILER_URL_OPTIONS_PORT"] %>
    protocol: <%= ENV["MAILER_URL_OPTIONS_PROTOCOL"] %>
    script_name: <%= ENV["MAILER_URL_OPTIONS_SCRIPTNAME"] %>