development:
        secret_key_base: somerandomkey
test:
        secret_key_base: somerandomkey
staging:
        secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
        secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
